---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: bootstrap
  src: https://github.com/alvistack/ansible-role-bootstrap/archive/master.tar.gz

- name: locales
  src: https://github.com/alvistack/ansible-role-locales/archive/master.tar.gz

- name: timezone
  src: https://github.com/alvistack/ansible-role-timezone/archive/master.tar.gz

- name: python
  src: https://github.com/alvistack/ansible-role-python/archive/master.tar.gz

- name: ansible
  src: https://github.com/alvistack/ansible-role-ansible/archive/master.tar.gz

- name: dumb-init
  src: https://github.com/alvistack/ansible-role-dumb-init/archive/master.tar.gz

- name: gosu
  src: https://github.com/alvistack/ansible-role-gosu/archive/master.tar.gz

- name: cvs
  src: https://github.com/alvistack/ansible-role-cvs/archive/master.tar.gz

- name: svn
  src: https://github.com/alvistack/ansible-role-svn/archive/master.tar.gz

- name: git
  src: https://github.com/alvistack/ansible-role-git/archive/master.tar.gz

- name: mercurial
  src: https://github.com/alvistack/ansible-role-mercurial/archive/master.tar.gz

- name: perforce
  src: https://github.com/alvistack/ansible-role-perforce/archive/master.tar.gz

- name: openjdk
  src: https://github.com/alvistack/ansible-role-openjdk/archive/master.tar.gz

- name: node
  src: https://github.com/alvistack/ansible-role-node/archive/master.tar.gz

- name: php
  src: https://github.com/alvistack/ansible-role-php/archive/master.tar.gz

- name: duplicity
  src: https://github.com/alvistack/ansible-role-duplicity/archive/master.tar.gz

- name: rclone
  src: https://github.com/alvistack/ansible-role-rclone/archive/master.tar.gz

- name: sshd
  src: https://github.com/alvistack/ansible-role-sshd/archive/master.tar.gz
